# Generated by Django 3.1.7 on 2021-03-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_url', models.URLField()),
                ('name_of_group', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('authors', models.TextField()),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('name_of_subgroup', models.TextField(null=True)),
            ],
        ),
    ]
