# Generated by Django 3.1.7 on 2021-03-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='authors',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='name_of_subgroup',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
