# Generated by Django 3.1.7 on 2021-03-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_news_app', '0002_auto_20210307_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='name_of_subgroup',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
