# Generated by Django 3.1.7 on 2021-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_news_app', '0003_auto_20210307_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
